# Generated by Django 3.2.7 on 2021-10-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senders_name', models.CharField(blank=True, max_length=300, null=True)),
                ('senders_phone_number', models.CharField(blank=True, max_length=300, null=True)),
                ('senders_email', models.CharField(blank=True, max_length=300, null=True)),
                ('pick_up_location', models.CharField(blank=True, max_length=300, null=True)),
                ('receivers_name', models.CharField(blank=True, max_length=300, null=True)),
                ('receivers_phone_number', models.CharField(blank=True, max_length=300, null=True)),
                ('receivers_email', models.CharField(blank=True, max_length=300, null=True)),
                ('receivers_location', models.CharField(blank=True, max_length=300, null=True)),
                ('item_weight', models.CharField(blank=True, max_length=300, null=True)),
                ('item_size', models.CharField(blank=True, max_length=300, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'logistics',
            },
        ),
    ]
