# Generated by Django 3.2.7 on 2021-10-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logistics',
            old_name='item_size',
            new_name='destination_city',
        ),
        migrations.RenameField(
            model_name='logistics',
            old_name='item_weight',
            new_name='destination_state',
        ),
        migrations.RenameField(
            model_name='logistics',
            old_name='receivers_email',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='logistics',
            old_name='pick_up_location',
            new_name='pick_up_city',
        ),
        migrations.RenameField(
            model_name='logistics',
            old_name='receivers_location',
            new_name='pick_up_state',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='receivers_name',
        ),
        migrations.RemoveField(
            model_name='logistics',
            name='receivers_phone_number',
        ),
    ]
