# Generated by Django 3.2.7 on 2021-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20211002_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistics',
            name='receivers_email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='logistics',
            name='receivers_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='logistics',
            name='receivers_phone_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
